### PR TITLE
Pull Request for Apple Website Clone

### PR DESCRIPTION
**Pull request by teekaytech**
## This is a solo project part of the positioning and floating elements curriculum. In this project, I successfully worked on the following:

- Embedded images
- Built a webpage using images as a background 
- Added gradients to elements
- Elements are aligned with float and flex or grid.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🚥 ♻️ 

Hi @teekaytech, you have done a great job 👍 Your README is professional, PR has a title and a short summary, commits are descriptive and great use of HTML semantics😄 Nice job 👍 , However, before we proceed, there are a few comments to address. Find comment below:
- ```Nav```: The first 8 elements should be links, currently the elements are not links. A quick fix is to wrap each of the first 8 elements with ```<a>```
las
- ```Main```: Let us fix two things here **[1]**. Let us give each of the ```<section>``` a unique class and let us reference the image with the ```background-image``` or ```background-url``` property. **[2]**. Let us wrap each of the ```<section>``` with the ```<a>``` so it can be clickable.
las1
- Let us add a link to the ```copyright``` in the ```<footer>```
las2

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
**You can find me on slack with this [Daniel Larbi Addo] for any clarification or help**

**Comment by teekaytech** [comment]
## Thank you, addod19 for your feedback.

The above corrections have been made and changes have been effected.
Kindly check out the updated project for the necessary action.

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @teekaytech . 😄 
### Very good job so far, you do an excellent work implementing the changes required by the previous TSE.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****
- [ ] Navbar blank space.
There's a blank space on the last 'li' element on the navbar.
Please fix it, you can put a fixed value to the navbar container.

Now. ⬇️ 

Screen Shot 2020-03-07 at 7 45 47 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-07 at 7 46 48 PM

****

- [ ]  Bottom images boxes.
The boxes below the background image on the main section should use the same width as the background image.

Now. ⬇️ 

Screen Shot 2020-03-07 at 7 50 26 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-07 at 7 51 20 PM

****

- [ ] HTML Validator.
There are some issues on the validator pleae fix it.

Screen Shot 2020-03-07 at 7 53 13 PM



****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by teekaytech** [comment]
## Thank you, davitomix for your feedback.
The above corrections have been made and changes have been effected.
Kindly check out the updated project for the necessary action.

**Comment by lekegitrepo** [comment]
### Hi @teekaytech 💯 🥇 
### Good job. This project is approved.

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved

**Pull request merged**
